### PR TITLE
Class C tested for EU_868

### PR DESCRIPTION
**Pull request by mr3188**
Low datarate optimization on AGC auto on for DR11 and DR12, otherwise CRC_ERROR is detected by RFM in CLASS C continuos mode.
Other minor changes.

### CODE REVIEW

**Comment by mr3188** [comment]
Tested with ChirpStack, TTN Madrid V7 board with ABP and OTAA. As this board is still in development I will try testing with V2 board based on Arduino Nano 328P

**Comment by mr3188** [comment]
On ARM MCU just using const puts contants in Flash memory but AVR needs PROGMEM macro. I added PROGMEM to be compatible with both microprocessors.

**Comment by mr3188** [comment]
Some of the problems I found testing Class C where related to the regional parameters, frequencies and data rates even working with TTN. I can only test with EU_868 so, if something goes wrong in other  regions, activate DEBUG and check values sent to FRM just before going continuous receive to see if it meets correct freq and data rate.

**Comment by mattjbailey** [comment]
I have not seen a good example of a working class C code yet. The default settings for this code are US915, yet no working examples for this band. Am I missing something? I have searched and searched with no luck.

**Pull request merged**
